### ISSUE TITLE
Code for importing and cleaning data for ED project

### ISSUE THREAD

**Issue by abbrenner-CBHC** [rin3-spring-2021/ED-Enhancement#2]
Hi Charlie and David,
I had some issues with various commands, but am most interested in knowing whether my data fits tidydata principles. I have some long strings (diagnoses, teams) that I have yet to deal with, and am struggling to figure out the best approach. 
Allison

**Comment by charliejhadley** [comment]
Thanks @abbrenner-CBHC ! Here's my feedback https://share.getcloudapp.com/WnuYp4gP

I didn't push my changes because I didn't know if they'd be useful - if you want them please comment here :)

**Comment by abbrenner-CBHC** [comment]
Charlie, yes, that would be wonderful! Thank you.

**Comment by charliejhadley** [comment]
@abbrenner-CBHC I've pushed these changes and squashed a merge conflict - check lines 90 - 92
