### ISSUE TITLE
Help getting data into correct form to use facet wrap in ggplot

### ISSUE THREAD

**Issue by abbrenner-CBHC** [rin3-spring-2021/ED-Enhancement#3]
Hi Charlie,
I am trying to create a plot to show totals of different types of emergency department utilization across client diagnoses. But I'm struggling to get the code to work, and am not sure if I am setting up the data correctly to accomplish my goal. What I want is to show variation in the types of utilization, as defined by a 1/0 flag (1=person fits into utilization category, 0=person does not fit into category) that I am trying to summarize across different diagnoses to show how certain diagnoses are associated with different patterns of utilization. 

The relevant code is in the input script file, and at the very end of the file with some explanation of my goals.

Thank you for your help!
Allison

**Comment by charliejhadley** [comment]
Hey @abbrenner-CBHC ! I've solved your plotting problem, which came down to using a string instead of a naked column name. There's hopefully a complete explanation in my feedback video https://share.getcloudapp.com/Jru4Yv2W
