### ISSUE TITLE
Adding more elements for data visualization to an older graph - Week 9 assignment

### ISSUE THREAD

**Issue by abbrenner-CBHC** [rin3-spring-2021/ED-Enhancement#4]
Hi Charlie,
I've updated my R markdown file to improve my graphing of ED visits over time (Figure 1). I've also tried to improve some tables as I build towards creating some elements of a report.
Thank you for your help and feedback, in addition to helping me with the merge conflicts in Git!
Allison

**Comment by charliejhadley** [comment]
I really need to start using {gt} in my own projects. Here's my feedback where I explain why you might have felt it took a long time to generate these charts https://share.getcloudapp.com/d5u1mZKQ
